### ISSUE TITLE
Zero Division Error

### ISSUE THREAD

**Issue by JordanShackelford** [vingtfranc/LoLAnalyzer#2]
Sorry I'm a little bit of a github noob. Not sure if I'm supposed to create an issue for this or if there is a way to just direct message you for help. 

I am training my own network. In python I ran "RunAll.py", it finished finding games and extracting them. Then it gave me a ZeroDivisionError

```
kr 7.20 all games downloaded
kr download complete
patch timestamps saved
-- Download complete --
0 game files found
0 new games to extract
Closing writer
-- Extraction complete --
-- Updating roles --
Traceback (most recent call last):
  File "RunAll.py", line 49, in <module>
    RoleUpdater.run(m)
  File "C:\Users\Jordan\Desktop\leaguenn\RoleUpdater.py", line 31, in run
    role_ratio[role] = 0 if role[0] not in role_count else role_count[role[0]] / s
ZeroDivisionError: division by zero
```

I tried starting over RunAll.py but I get the same error

**Comment by VRichardJP** [comment]
seems like something is wrong with the extraction, can you give me a few lines of an extracted data file?
you should get something like this:
```
s_alistar,s_annie,s_ashe,s_fiddlesticks,s_jax,s_kayle,s_masteryi,s_morgana,s_nunu,s_ryze,s_sion,s_sivir,s_soraka,s_teemo,s_tristana,s_twistedfate,s_warwick,s_singed,s_zilean,s_evelynn,s_tryndamere,s_twitch,s_karthus,s_amumu,s_chogath,s_anivia,s_rammus,s_veigar,s_kassadin,s_gangplank,s_taric,s_blitzcrank,s_drmundo,s_janna,s_malphite,s_corki,s_katarina,s_nasus,s_heimerdinger,s_shaco,s_udyr,s_nidalee,s_poppy,s_gragas,s_pantheon,s_mordekaiser,s_ezreal,s_shen,s_kennen,s_garen,s_akali,s_malzahar,s_olaf,s_kogmaw,s_xinzhao,s_vladimir,s_galio,s_urgot,s_missfortune,s_sona,s_swain,s_lux,s_leblanc,s_irelia,s_trundle,s_cassiopeia,s_caitlyn,s_renekton,s_karma,s_maokai,s_jarvaniv,s_nocturne,s_leesin,s_brand,s_rumble,s_vayne,s_orianna,s_yorick,s_leona,s_wukong,s_skarner,s_talon,s_riven,s_xerath,s_graves,s_shyvana,s_fizz,s_volibear,s_ahri,s_viktor,s_sejuani,s_ziggs,s_nautilus,s_fiora,s_lulu,s_hecarim,s_varus,s_darius,s_draven,s_jayce,s_zyra,s_diana,s_rengar,s_syndra,s_khazix,s_elise,s_zed,s_nami,s_vi,s_thresh,s_quinn,s_zac,s_lissandra,s_aatrox,s_lucian,s_jinx,s_yasuo,s_velkoz,s_braum,s_gnar,s_azir,s_kalista,s_reksai,s_bard,s_ekko,s_tahmkench,s_kindred,s_illaoi,s_jhin,s_aurelionsol,s_taliyah,s_kled,s_ivern,s_camille,s_rakan,s_xayah,s_kayn,s_ornn,p_alistar,p_annie,p_ashe,p_fiddlesticks,p_jax,p_kayle,p_masteryi,p_morgana,p_nunu,p_ryze,p_sion,p_sivir,p_soraka,p_teemo,p_tristana,p_twistedfate,p_warwick,p_singed,p_zilean,p_evelynn,p_tryndamere,p_twitch,p_karthus,p_amumu,p_chogath,p_anivia,p_rammus,p_veigar,p_kassadin,p_gangplank,p_taric,p_blitzcrank,p_drmundo,p_janna,p_malphite,p_corki,p_katarina,p_nasus,p_heimerdinger,p_shaco,p_udyr,p_nidalee,p_poppy,p_gragas,p_pantheon,p_mordekaiser,p_ezreal,p_shen,p_kennen,p_garen,p_akali,p_malzahar,p_olaf,p_kogmaw,p_xinzhao,p_vladimir,p_galio,p_urgot,p_missfortune,p_sona,p_swain,p_lux,p_leblanc,p_irelia,p_trundle,p_cassiopeia,p_caitlyn,p_renekton,p_karma,p_maokai,p_jarvaniv,p_nocturne,p_leesin,p_brand,p_rumble,p_vayne,p_orianna,p_yorick,p_leona,p_wukong,p_skarner,p_talon,p_riven,p_xerath,p_graves,p_shyvana,p_fizz,p_volibear,p_ahri,p_viktor,p_sejuani,p_ziggs,p_nautilus,p_fiora,p_lulu,p_hecarim,p_varus,p_darius,p_draven,p_jayce,p_zyra,p_diana,p_rengar,p_syndra,p_khazix,p_elise,p_zed,p_nami,p_vi,p_thresh,p_quinn,p_zac,p_lissandra,p_aatrox,p_lucian,p_jinx,p_yasuo,p_velkoz,p_braum,p_gnar,p_azir,p_kalista,p_reksai,p_bard,p_ekko,p_tahmkench,p_kindred,p_illaoi,p_jhin,p_aurelionsol,p_taliyah,p_kled,p_ivern,p_camille,p_rakan,p_xayah,p_kayn,p_ornn,patch,win,file
A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,7_17,1,1789577234
A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,N,A,A,A,A,A,A,A,A,N,A,A,A,N,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,N,A,A,A,A,A,A,N,A,A,A,A,A,A,A,A,A,A,A,A,A,N,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,N,A,A,A,A,A,A,A,A,A,N,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,7_17,1,1789577234
A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,N,A,A,A,A,A,A,A,A,N,A,A,A,N,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,N,A,A,A,A,A,A,N,A,A,A,A,A,A,A,A,A,A,A,A,A,N,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,N,A,A,A,A,A,A,A,A,A,N,A,A,A,A,A,A,A,B,A,A,A,A,A,A,A,A,A,A,A,A,A,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,M,N,N,N,N,N,N,N,N,N,N,N,N,N,7_17,1,1789577234
A,A,A,A,A,A,A,A,R,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,N,A,A,A,A,A,A,A,A,N,A,A,A,N,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,N,A,A,A,A,A,A,N,A,A,A,A,A,A,A,A,A,A,A,A,A,N,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,N,A,A,A,A,A,A,A,A,A,N,A,A,A,A,A,A,A,B,A,A,A,A,A,A,A,A,A,A,A,A,A,N,N,N,N,N,N,N,N,J,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,M,N,N,N,N,N,N,N,N,N,N,N,N,N,7_17,1,1789577234
A,A,A,A,A,A,A,A,R,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,N,A,A,A,A,A,A,A,A,N,A,A,A,N,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,N,A,A,A,A,A,A,N,A,A,A,A,A,A,A,A,A,A,A,A,A,N,A,A,A,R,A,A,A,A,A,A,A,A,A,A,A,N,A,A,A,A,A,A,A,A,A,N,A,A,A,A,A,A,A,B,A,A,A,A,A,A,A,A,A,A,A,A,A,N,N,N,N,N,N,N,N,J,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,S,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,M,N,N,N,N,N,N,N,N,N,N,N,N,N,7_17,1,1789577234
A,A,A,A,A,A,A,A,R,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,N,A,A,A,A,A,A,A,A,N,B,A,A,N,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,N,A,A,A,A,A,A,N,A,A,A,A,A,A,A,A,A,A,A,A,A,N,A,A,A,R,A,A,A,A,A,A,A,A,A,A,A,N,A,A,A,A,A,A,A,A,A,N,A,A,A,A,A,A,A,B,A,A,A,A,A,A,A,A,A,A,A,A,A,N,N,N,N,N,N,N,N,J,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,T,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,S,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,M,N,N,N,N,N,N,N,N,N,N,N,N,N,7_17,1,1789577234
A,A,A,A,A,A,A,A,R,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,N,A,A,A,A,A,A,A,A,N,B,A,A,N,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,B,A,A,A,A,A,A,A,A,A,N,A,A,A,A,A,A,N,A,A,A,A,A,A,A,A,A,A,A,A,A,N,A,A,A,R,A,A,A,A,A,A,A,A,A,A,A,N,A,A,A,A,A,A,A,A,A,N,A,A,A,A,A,A,A,B,A,A,A,A,A,A,A,A,A,A,A,A,A,N,N,N,N,N,N,N,N,J,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,T,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,S,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,S,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,M,N,N,N,N,N,N,N,N,N,N,N,N,N,7_17,1,1789577234
A,A,A,A,A,A,A,A,R,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,N,A,A,A,A,A,A,A,A,N,B,A,A,N,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,R,A,A,A,A,A,B,A,A,A,A,A,A,A,A,A,N,A,A,A,A,A,A,N,A,A,A,A,A,A,A,A,A,A,A,A,A,N,A,A,A,R,A,A,A,A,A,A,A,A,A,A,A,N,A,A,A,A,A,A,A,A,A,N,A,A,A,A,A,A,A,B,A,A,A,A,A,A,A,A,A,A,A,A,A,N,N,N,N,N,N,N,N,J,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,T,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,C,N,N,N,N,N,S,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,S,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,M,N,N,N,N,N,N,N,N,N,N,N,N,N,7_17,1,1789577234
A,A,A,A,A,A,A,A,R,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,N,A,A,A,A,A,A,A,A,N,B,A,A,N,A,A,A,A,A,A,A,A,A,A,A,A,A,R,A,R,A,A,A,A,A,B,A,A,A,A,A,A,A,A,A,N,A,A,A,A,A,A,N,A,A,A,A,A,A,A,A,A,A,A,A,A,N,A,A,A,R,A,A,A,A,A,A,A,A,A,A,A,N,A,A,A,A,A,A,A,A,A,N,A,A,A,A,A,A,A,B,A,A,A,A,A,A,A,A,A,A,A,A,A,N,N,N,N,N,N,N,N,J,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,T,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,M,N,C,N,N,N,N,N,S,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,S,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,M,N,N,N,N,N,N,N,N,N,N,N,N,N,7_17,1,1789577234
A,A,A,A,A,A,A,A,R,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,N,A,A,A,A,A,A,A,A,N,B,A,A,N,A,A,A,A,A,A,A,A,A,A,A,A,A,R,A,R,A,A,A,A,A,B,A,A,A,A,A,A,A,A,A,N,A,A,A,A,A,A,N,A,A,A,A,A,A,A,A,A,A,A,A,A,N,A,A,A,R,A,A,A,A,A,A,A,A,A,B,A,N,A,A,A,A,A,A,A,A,A,N,A,A,A,A,A,A,A,B,A,A,A,A,A,A,A,A,A,A,A,A,A,N,N,N,N,N,N,N,N,J,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,T,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,M,N,C,N,N,N,N,N,S,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,S,N,N,N,N,N,N,N,N,N,J,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,M,N,N,N,N,N,N,N,N,N,N,N,N,N,7_17,1,1789577234
A,A,A,A,A,A,A,A,R,A,A,A,A,A,B,A,A,A,A,A,A,A,A,A,N,A,A,A,A,A,A,A,A,N,B,A,A,N,A,A,A,A,A,A,A,A,A,A,A,A,A,R,A,R,A,A,A,A,A,B,A,A,A,A,A,A,A,A,A,N,A,A,A,A,A,A,N,A,A,A,A,A,A,A,A,A,A,A,A,A,N,A,A,A,R,A,A,A,A,A,A,A,A,A,B,A,N,A,A,A,A,A,A,A,A,A,N,A,A,A,A,A,A,A,B,A,A,A,A,A,A,A,A,A,A,A,A,A,N,N,N,N,N,N,N,N,J,N,N,N,N,N,C,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,T,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,M,N,C,N,N,N,N,N,S,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,S,N,N,N,N,N,N,N,N,N,J,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,M,N,N,N,N,N,N,N,N,N,N,N,N,N,7_17,1,1789577234
A,A,A,A,A,A,A,A,R,A,A,A,A,A,B,A,A,A,A,A,A,A,A,A,N,A,A,A,A,A,A,A,A,N,B,A,A,N,A,A,A,A,A,A,A,A,A,A,A,A,A,R,A,R,A,A,A,A,A,B,A,A,A,A,A,A,A,A,A,N,A,A,A,A,A,A,N,A,A,A,A,A,A,A,A,A,A,A,A,A,N,A,A,A,R,A,A,A,A,A,A,A,A,A,B,A,N,A,A,A,A,A,A,A,A,A,N,A,A,A,A,A,A,A,B,A,A,A,A,A,A,A,A,A,A,A,R,A,N,N,N,N,N,N,N,N,J,N,N,N,N,N,C,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,T,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,M,N,C,N,N,N,N,N,S,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,S,N,N,N,N,N,N,N,N,N,J,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,M,N,N,N,N,N,N,N,N,N,N,N,T,N,7_17,1,1789577234
```

**Comment by JordanShackelford** [comment]
Hmm. The extracted file is completely empty. Nothing in there at all

**Comment by VRichardJP** [comment]
try to delete both extracted folder and extracted.txt. Then make sure you have some files under patches/7.20/kr (size is about 14KB each). Also make sure that the options are correct in RunAll.py:
```
m = Modes.ABR_TJMCS_Mode(['7.20'])
n = Networks.DenseUniform(mode=m, n_hidden_layers=5, NN=1024, dropout=0.2, batch_size=1000, report=1)
```
I guess you still have the old `['7.16', '7.17']` (since you would have no game from 7.16 and 7.17, the script does not find any game to extract)

**Comment by JordanShackelford** [comment]
You're right, It still says `m = Modes.ABR_TJMCS_Mode(['7.16', '7.17'])`
I'll update it
