### ISSUE TITLE
DataShuffling pop from empty

### ISSUE THREAD

**Issue by nongnoobjung** [vingtfranc/LoLAnalyzer#5]
Traceback (most recent call last):
  File ".\RunAll.py", line 55, in <module>
    DataShuffling.run(m, shuffling_files, keep_for_testing, cpu)
  File "C:\Users\Admin\Desktop\lol\DataShuffling.py", line 68, in run
    testing_file = preprocessed_files.pop(0)  # take data away for testing
IndexError: pop from empty list
PS C:\Users\Admin\Desktop\lol> s

**Comment by VRichardJP** [comment]
check this: https://github.com/vingtfranc/LoLAnalyzer/issues/3
